### PR TITLE
Add missing properties to ValueMetadata

### PR DESCRIPTION
**Pull request by spudwebb**
The properties added are used by the Configuration command class values.

### CODE REVIEW

**Comment by spudwebb** [comment]
@marcus-j-davies  I added a commit that adds a ValueFormat parameter to  ZWJSS_SetRawConfigParameterValue method, because ZWaveJS complain that if you specify valueSize you need to specify valueFormat as well

**Comment by marcus-j-davies** [comment]
Thanks @spudwebb  - I marked this as a `FIXME` for that reason,I'll get it merged this evening.

**Comment by marcus-j-davies** [comment]
@spudwebb 


I think we should add the enums here?

https://github.com/zwave-js/node-zwave-js/blob/9549a040477364b54a2df617a42fd30639e67e14/packages/core/src/values/Metadata.ts#L157

**Comment by spudwebb** [comment]
I agree, I can do it tomorrow.

**Comment by marcus-j-davies** [comment]
I'm here, so will do it shortly, and merge 👍

**Comment by marcus-j-davies** [comment]
@spudwebb 

I have added all variants according to the Options object variants. 
https://github.com/zwave-js/node-zwave-js/blob/9549a040477364b54a2df617a42fd30639e67e14/packages/cc/src/cc/ConfigurationCC.ts#L107

```csharp
// Variant 1: Normal parameter, defined in a config file
public Task<CMDResult> ZWJSS_SetRawConfigParameterValue(int Parameter, int Value)


// Variant 2: Normal parameter, not defined in a config file
public Task<CMDResult> ZWJSS_SetRawConfigParameterValue(int Parameter, int Value, int ValueSize, Enums.ConfigValueFormat ValueFormat)

//Variant 3: Partial parameter, must be defined in a config file
public Task<CMDResult> ZWJSS_SetRawConfigParameterValue(int Parameter, int Bitmask, int Value)
 ```

**Pull request merged**
