### PR TITLE
Add possibility to listen to logging events

### PR DESCRIPTION
**Pull request by spudwebb**
I created methods to start and stop listening for logging events as per https://github.com/zwave-js/zwave-js-server#start-listening-to-logging-events
I did not implement the optional filter parameter as I'm not sure of how it works, and I couldn't find any documentation about it.

### CODE REVIEW

**Comment by marcus-j-davies** [comment]
Thanks @spudwebb for the contribution - its always welcome!

Initial review looks great!

I'll review in more detail soon, I am aiming to update the library to the latest Server API offerings, so I may retarget this PR to the 3.1.0 Branch once I have fully reviewed, that aims to bring it up to date.

I want to update the web socket client code also, I'm not not keen on it currently.

until then - Many many thanks 👍

**Comment by marcus-j-davies** [comment]
HI @spudwebb 

I have had time to look at this.
I do have a comment..

I wonder if we should move this outside of the `Driver` class somehow?

You see, Im trying to remain faithful in the exposed methods that are offered by the Native JS Module and its namespaces.
I wonder if we can do something along the lines of...

`Driver.ImplementationExtras.StartListeningLogs()`

But then in saying that, I have properties and events, that are not native in the Driver, so I'm questioning my own choices here 😅

**Comment by spudwebb** [comment]
@marcus-j-davies, I think I understand what you mean, but in the Z-Wave JS Server project itself this command is included in the [`DriverCommand enum`](https://github.com/zwave-js/zwave-js-server/blob/e4c6625c5b12ba4358d9503d65e79a15c3876365/src/lib/driver/command.ts#L8)  and its full name is "driver.start_listening_logs" that' s why I added it to the `Driver `class.

Anyway I don' t have a strong preference, so whatever you think is best will be fine with me.

**Comment by marcus-j-davies** [comment]
No problem.

I'll wait to see what @raman325 responds with.
if this is a utility method offered by the server its self, I'm tempted to move them to an `ImplementationExtras` class.

Keeping the `Driver` class as native as possible with its JS counter part. 👍

**Comment by raman325** [comment]
that's a good point, yes this is a utility method that the server adds which creates a custom transport to forward the logs over the websocket. Something to consider updating in the server too, we have server level commands so there's an existing pattern to follow

**Comment by marcus-j-davies** [comment]
Cool,
For the .NET library, I'm going to partition these utilities away from the Driver class.

@spudwebb,
Thanks for the PR - I'll merge it into the 4.0.0 branch, and will take it from there 👍

**Pull request merged**
