### PR TITLE
Add NodeAlive event to the ZWaveNode class, and add lastSeen property to the NodeStatistics class.

### PR DESCRIPTION
**Pull request by spudwebb**

### CODE REVIEW

**Comment by marcus-j-davies** [comment]
No idea why I didn't include **Alive** (the most basic of events 😮 ) - Thanks!
Will get it merged tonight!

**Comment by marcus-j-davies** [comment]
@spudwebb 

Can you do me favour?

set `lastSeen`, in  the `statistics`, and `ZWaveNode` class  (its there also) as `DateTime` 

The original output should hopefully be **ISO 8601** and Im thinking it should parse to `DateTime`?

I have no way to test on my system currently

**Comment by spudwebb** [comment]
yes it parses to DateTime. 2 questions:

1. lastSeen reported by ZWave JS seems to be an UTC time, do we want to convert it to a local time or do we want to keep it as UTC?
2. when it is null, it is parsed as 0001-01-01T00:00:00 because `DateTime `is a struct and it is its default value. Do we want to use a nullable property instead `DateTime?`, so that we can have a null value for this property?

**Comment by marcus-j-davies** [comment]
1) My Vote is UTC - allow the front end to massage as seems fit?
2) I think a `nullable` object (I think we have a few in place already)

**Comment by spudwebb** [comment]
Done and tested.

**Comment by marcus-j-davies** [comment]
Merged!

**Pull request merged**
